---
- hosts: all
  become: yes

  tasks:
   - name: install git tree and wget on ubuntu
     apt:
      name: "{{ item }}"
      state: present
     with_items: 
     - git
     - wget
     - tree
     when: ansible_os_family== "Debian" 
     
   - name: install tree wget and git on RedHat
     yum:
      name: "{{ item }}"
      state: present
     with_items:
      - git
      - tree
      - wget
     when: ansible_os_family== "RedHat"



    
        