---
- hosts: all
  become: yes
  tasks:
    

  - name: install apache on ubuntu(apache2)
    apt:
     name: apache2
     state: present

  - name: start the service
    service:
     name: apache2
     state: started   


